### ISSUE TITLE
报错2个:安装报错和运行报错

### ISSUE THREAD

**Issue by KuYouRan** [CodeCrafter-TL/python-cmd#1]
--日志开始--
error: subprocess-exited-with-error

  × Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'PyQt5.sip' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyQt5-sip
Failed to build PyQt5-sip

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (PyQt5-sip)
--日志结束--

--日志开始--
E:\github_project\python-cmd>python3 main.py
  File "main.py", line 83
    welcome = f"{name} {version}\n{\
              ^
SyntaxError: f-string expression part cannot include a backslash
--日志结束--
python版本是3.13
pip版本是24.2
查看图片可以更明确的区分报错关键信息
![python-cmd-Snipaste_2024-11-18_15-58-35](https://github.com/user-attachments/assets/cfcc40d3-2be5-4c35-bd3e-12b77f247763)
![python-cmd-Snipaste_2024-11-18_15-59-08](https://github.com/user-attachments/assets/43d9bfb9-3a07-484c-a4cd-245928d98659)
![python-version-Snipaste_2024-11-18_15-59-43](https://github.com/user-attachments/assets/a3aa4df2-66ec-4aae-bcf6-91705ef1d511)

**Comment by Mengobs** [comment]
感谢您反馈您使用中遇到的问题！安装报错根据信息可得是缺少编译工具，可以去它提供的网址里下载。使用报错是因为我们在f-string中使用了反斜杠，貌似是3.13新出的规则（3.12没有遇到此问题。您可以将反斜杠删除以继续使用。


CodeCrafter-TL
***@***.***








------------------ 原始邮件 ------------------
发件人: KuYouRan ***@***.***&gt;
发送时间: 2024年11月18日 16:01
收件人: CodeCrafter-TL/python-cmd ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [CodeCrafter-TL/python-cmd] 报错2个:安装报错和运行报错 (Issue #1)





 
--日志开始--
 error: subprocess-exited-with-error
 
× Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.
 │ exit code: 1
 ╰─&gt; [5 lines of output]
 running bdist_wheel
 running build
 running build_ext
 building 'PyQt5.sip' extension
 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
 [end of output]
 
note: This error originates from a subprocess, and is likely not a problem with pip.
 ERROR: Failed building wheel for PyQt5-sip
 Failed to build PyQt5-sip
 
[notice] A new release of pip is available: 24.2 -&gt; 24.3.1
 [notice] To update, run: python.exe -m pip install --upgrade pip
 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (PyQt5-sip)
 --日志结束--
 
--日志开始--
 E:\github_project\python-cmd&gt;python3 main.py
 File "main.py", line 83
 welcome = f"{name} {version}\n{
 ^
 SyntaxError: f-string expression part cannot include a backslash
 --日志结束--
 python版本是3.13
 pip版本是24.2
 查看图片可以更明确的区分报错关键信息
 python-cmd-Snipaste_2024-11-18_15-58-35.png (view on web)
 python-cmd-Snipaste_2024-11-18_15-59-08.png (view on web)
 python-version-Snipaste_2024-11-18_15-59-43.png (view on web)
